zend_extension=xdebug.so
xdebug.mode=develop,debug
xdebug.start_with_request=trigger # Cambiado a 'trigger' para mejor rendimiento
; Añadido para mayor claridad
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
